### ISSUE TITLE
Can't access settings

### ISSUE THREAD

**Issue by fabfo** [AdrienDesola/gladys-spotify#3]
Hi

I installed spotify module and after install i couldn't go to the settings , I had the following error in the log
> Sending 500 ("Server Error") response:
>  TypeError: Cannot read property 'setup' of undefined
>     at Object.module.exports [as config] (/root/gladys/api/core/module/module.config.js:5:43)
>     at Object.config (/root/gladys/api/controllers/ModuleController.js:35:23)
>     at wrapper (/root/gladys/node_modules/@sailshq/lodash/lib/index.js:3250:19)
>     at routeTargetFnWrapper (/root/gladys/node_modules/sails/lib/router/bind.js:181:5)
>     ...

But then i saw this line in log as well :

> Module spotify-connect installed with success. Need reboot.

So i rebooted Gladys.
Now, i still can't access to settings and i have the following error in the logs when i try.
> TypeError: Cannot read property 'createAuthorizeURL' of null
>     at Hook.setup (/root/gladys/api/hooks/spotify-connect/lib/setup.js:22:33)
>     at Hook.wrapper [as setup] (/root/gladys/node_modules/@sailshq/lodash/lib/index.js:3250:19)
>     at Object.module.exports [as config] (/root/gladys/api/core/module/module.config.js:9:43)
>     at Object.config (/root/gladys/api/controllers/ModuleController.js:35:23)
> ...

I think the module didn't init correctly. I saw this error in the init step

> Unhandled rejection Error: Param spotify_client_id not found
>     at /root/gladys/api/core/param/param.getValue.js:16:36
>     at tryCatcher (/root/gladys/node_modules/bluebird/js/release/util.js:16:23)
>     at Promise._settlePromiseFromHandler (/root/gladys/node_modules/bluebird/js/release/promise.js:512:31)
>     at Promise._settlePromise (/root/gladys/node_modules/bluebird/js/release/promise.js:569:18)
>     at Promise._settlePromise0 (/root/gladys/node_modules/bluebird/js/release/promise.js:614:10)
>     at Promise._settlePromises (/root/gladys/node_modules/bluebird/js/release/promise.js:693:18)
>     at Promise._fulfill (/root/gladys/node_modules/bluebird/js/release/promise.js:638:18)

I guess it's because i didn't set the values before rebooting gladys. But the settings of any modules seems not accessible after install until gladys reboot.

When i supposed to can access settings ?

**Comment by fabfo** [comment]
Sorry, my bad, I didn't understand how the settings work. I didn't see that they had to be configured in Settings> Settings.
