### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by morganorix** [AdrienDesola/gladys-spotify#7]
I have make the tutorial.
But When i've execute the script test i've an error message in the gladys logs : 
```
0|gladys   | gladys.utils.sqlUnique was not able to find element
0|gladys   | Query = "
0|gladys   |             SELECT dt.id, dt.type, dt.unit, dt.min, dt.max, d.identifier, dt.device, d.service, d.machine, dt.identifier as deviceTypeIdentifier
0|gladys   |             FROM devicetype dt 
0|gladys   |             JOIN device d ON d.id = dt.device
0|gladys   |             WHERE dt.type = 'music'
0|gladys   |             LIMIT 1;
0|gladys   |     "
0|gladys   | Params = "[]"
0|gladys   | Unhandled rejection Error: NotFound
0|gladys   |     at /home/pi/gladys/api/core/utils/utils.sqlUnique.js:11:31
0|gladys   |     at tryCatcher (/home/pi/gladys/node_modules/bluebird/js/release/util.js:16:23)
0|gladys   |     at Promise._settlePromiseFromHandler (/home/pi/gladys/node_modules/bluebird/js/release/promise.js:512:31)
0|gladys   |     at Promise._settlePromise (/home/pi/gladys/node_modules/bluebird/js/release/promise.js:569:18)
0|gladys   |     at Promise._settlePromise0 (/home/pi/gladys/node_modules/bluebird/js/release/promise.js:614:10)
0|gladys   |     at Promise._settlePromises (/home/pi/gladys/node_modules/bluebird/js/release/promise.js:693:18)
0|gladys   |     at Promise._fulfill (/home/pi/gladys/node_modules/bluebird/js/release/promise.js:638:18)
0|gladys   |     at /home/pi/gladys/node_modules/bluebird/js/release/nodeback.js:42:21
0|gladys   |     at /home/pi/gladys/node_modules/sails-mysql/lib/connections/spawn.js:120:16
0|gladys   |     at Object.poolfully [as releaseConnection] (/home/pi/gladys/node_modules/sails-mysql/lib/connections/release.js:28:12)
0|gladys   |     at Query._callback (/home/pi/gladys/node_modules/sails-mysql/lib/connections/spawn.js:105:35)
0|gladys   |     at Query.Sequence.end (/home/pi/gladys/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
0|gladys   |     at Query._handleFinalResultPacket (/home/pi/gladys/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
0|gladys   |     at Query.EofPacket (/home/pi/gladys/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
0|gladys   |     at Protocol._parsePacket (/home/pi/gladys/node_modules/mysql/lib/protocol/Protocol.js:280:23)
0|gladys   |     at Parser.write (/home/pi/gladys/node_modules/mysql/lib/protocol/Parser.js:73:12)
0|gladys   |     at Protocol.write (/home/pi/gladys/node_modules/mysql/lib/protocol/Protocol.js:39:16)
0|gladys   |     at Socket.<anonymous> (/home/pi/gladys/node_modules/mysql/lib/Connection.js:96:28)
0|gladys   |     at emitOne (events.js:116:13)
0|gladys   |     at Socket.emit (events.js:211:7)
0|gladys   |     at addChunk (_stream_readable.js:263:12)
0|gladys   |     at readableAddChunk (_stream_readable.js:250:11)
0|gladys   | House : checkUsersPresence
0|gladys   | House : checkUsersPresence
```

<img width="823" alt="capture d ecran 2019-03-02 a 13 45 48" src="https://user-images.githubusercontent.com/4254819/53682102-b05abe80-3cf2-11e9-8f2a-d24be2b7024b.png">

I'm configure in https and i'm valided the generate link with a successful message. The token is in the parameter.

![capture d ecran 2019-03-02 a 13 46 16](https://user-images.githubusercontent.com/4254819/53682099-a769ed00-3cf2-11e9-95b4-520f851ec087.png)

**Comment by Pierre-Gilles** [comment]
I realized the tutorial is not valid, the test script should be : 

```javascript
gladys.modules['spotify-connect'].music.playPlaylist('spotify:album:4ydl8Ci7OsndhI2ALnrpIv');
```
